In [1]:
import pandas as pd
import numpy as np
from numpy.random import RandomState
from numpy.linalg import cholesky

from cellregmap import run_association, run_interaction, estimate_betas


import gxslmm as gs

In [2]:
random = RandomState(1)
n = 50                               # number of samples (cells)
p = 5                                # number of individuals
k = 4                                # number of contexts
y = random.randn(n, 1)               # outcome vector (expression phenotype, one gene only)
W = np.ones((n, 1))                     # intercept (covariate matrix)
hK = random.randn(n, p)              # decomposition of kinship matrix (K = hK @ hK.T)
random = RandomState(3)
hS = random.randn(n, p)              # decomposition of Spatial kernel (S = hS @ hS.T)
x = 1.0 * (random.rand(n, 1) < 0.2)  # SNP vector

In [3]:
hK

array([[ 3.00170320e-01, -3.52249846e-01, -1.14251820e+00,
        -3.49342722e-01, -2.08894233e-01],
       [ 5.86623191e-01,  8.38983414e-01,  9.31102081e-01,
         2.85587325e-01,  8.85141164e-01],
       [-7.54397941e-01,  1.25286816e+00,  5.12929820e-01,
        -2.98092835e-01,  4.88518147e-01],
       [-7.55717130e-02,  1.13162939e+00,  1.51981682e+00,
         2.18557541e+00, -1.39649634e+00],
       [-1.44411381e+00, -5.04465863e-01,  1.60037069e-01,
         8.76168921e-01,  3.15634947e-01],
       [-2.02220122e+00, -3.06204013e-01,  8.27974643e-01,
         2.30094735e-01,  7.62011180e-01],
       [-2.22328143e-01, -2.00758069e-01,  1.86561391e-01,
         4.10051647e-01,  1.98299720e-01],
       [ 1.19008646e-01, -6.70662286e-01,  3.77563786e-01,
         1.21821271e-01,  1.12948391e+00],
       [ 1.19891788e+00,  1.85156417e-01, -3.75284950e-01,
        -6.38730407e-01,  4.23494354e-01],
       [ 7.73400683e-02, -3.43853676e-01,  4.35968568e-02,
        -6.20000844e-01

In [4]:
S = hS @ hS.T
print(S.shape)

K = hK @ hK.T
print(K.shape)


(50, 50)
(50, 50)


In [5]:
K

array([[ 1.68520715, -1.46791472, -1.2517142 , ...,  0.22823683,
        -0.34304934, -0.92149098],
       [-1.46791472,  2.78000602,  1.43345428, ...,  0.05547911,
         0.03209465,  1.15212777],
       [-1.2517142 ,  1.43345428,  2.72940119, ...,  0.32466572,
         0.4837169 ,  1.72071916],
       ...,
       [ 0.22823683,  0.05547911,  0.32466572, ...,  1.32929681,
         0.80002312,  1.19728795],
       [-0.34304934,  0.03209465,  0.4837169 , ...,  0.80002312,
         0.75090037,  1.01896275],
       [-0.92149098,  1.15212777,  1.72071916, ...,  1.19728795,
         1.01896275,  2.13455849]])

In [6]:
new_hK = gs.buildchol(K) # K = hK @ hK.T
# new_hK = cholesky(K) # K = hK @ hK.T
new_hK @ new_hK.T

array([[ 1.68520715, -1.46791472, -1.2517142 , ...,  0.22823683,
        -0.34304934, -0.92149098],
       [-1.46791472,  2.78000602,  1.43345428, ...,  0.05547911,
         0.03209465,  1.15212777],
       [-1.2517142 ,  1.43345428,  2.72940119, ...,  0.32466572,
         0.4837169 ,  1.72071916],
       ...,
       [ 0.22823683,  0.05547911,  0.32466572, ...,  1.32929681,
         0.80002312,  1.19728795],
       [-0.34304934,  0.03209465,  0.4837169 , ...,  0.80002312,
         0.75090037,  1.01896275],
       [-0.92149098,  1.15212777,  1.72071916, ...,  1.19728795,
         1.01896275,  2.13455849]])

In [7]:
S

array([[ 6.9485937 , -0.51712397, -5.07848024, ...,  0.64785841,
        -0.68042035,  1.78495017],
       [-0.51712397,  0.75548702, -0.25846397, ...,  0.77110514,
        -1.35706127, -2.14146879],
       [-5.07848024, -0.25846397,  6.21066226, ..., -0.29019682,
         4.52690861,  1.71506242],
       ...,
       [ 0.64785841,  0.77110514, -0.29019682, ...,  2.02681143,
        -1.12109613, -0.33106667],
       [-0.68042035, -1.35706127,  4.52690861, ..., -1.12109613,
         8.8480685 ,  4.16575015],
       [ 1.78495017, -2.14146879,  1.71506242, ..., -0.33106667,
         4.16575015,  9.35408384]])

In [8]:
new_hS = gs.buildchol(S) # S = hS @ hS.T
new_hS @ new_hS.T

array([[ 6.9485937 , -0.51712397, -5.07848024, ...,  0.64785841,
        -0.68042035,  1.78495017],
       [-0.51712397,  0.75548702, -0.25846397, ...,  0.77110514,
        -1.35706127, -2.14146879],
       [-5.07848024, -0.25846397,  6.21066226, ..., -0.29019682,
         4.52690861,  1.71506242],
       ...,
       [ 0.64785841,  0.77110514, -0.29019682, ...,  2.02681143,
        -1.12109613, -0.33106667],
       [-0.68042035, -1.35706127,  4.52690861, ..., -1.12109613,
         8.8480685 ,  4.16575015],
       [ 1.78495017, -2.14146879,  1.71506242, ..., -0.33106667,
         4.16575015,  9.35408384]])

In [9]:
gs.gxslmm(y = y, x = x, W = W, S = new_hS, K = new_hK)

100%|██████████| 1/1 [00:00<00:00, 10.60it/s]


p_association  p_interaction  rho1_association  e2_association  \
0            1.0       0.834583               0.0             0.0   

   g2_association  eps2_association  rho1_interaction  e2_interaction  \
0        0.202924          0.079283               0.0             0.0   

   g2_interaction  eps2_interaction  
0        0.020776          0.951671